version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 saas_platform.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-^xnbgnj*4x!b_zv#kvc!d49_dvwemnw=!9ay@850y9harw^rte}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-192.168.1.31,acme.local,localhost,*.local}
      - DB_ENGINE=django_tenants.postgresql_backend
      - DB_NAME=${DB_NAME:-saas_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_HOST=db
      - DB_PORT=5432
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT:-False}
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-False}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-False}
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-saas_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}

volumes:
  postgres_data:
  static_volume:
  media_volume: